# Generated by Django 4.2.4 on 2024-06-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cusfirst_name', models.CharField(max_length=100)),
                ('Cuslast_name', models.CharField(max_length=100)),
                ('Cusemail', models.CharField(max_length=100)),
                ('Cusphone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ex_email', models.CharField(max_length=100)),
                ('Ex_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productQuantity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_first_name', models.CharField(max_length=100)),
                ('Reg_last_name', models.CharField(max_length=100)),
                ('Reg_email', models.CharField(max_length=100)),
                ('Reg_password', models.CharField(max_length=100)),
            ],
        ),
    ]
