# Generated by Django 4.2.4 on 2024-06-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_latest', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
    ]
