# Generated by Django 4.2.4 on 2024-06-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('add_product', models.CharField(max_length=100)),
            ],
        ),
    ]
