# Generated by Django 4.2.4 on 2024-07-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_addstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='AddOrder',
            new_name='Stock',
        ),
        migrations.DeleteModel(
            name='AddStock',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='add_product',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='user',
            new_name='item',
        ),
    ]
