# Generated by Django 4.2.4 on 2024-07-09 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_order_rename_addorder_stock_delete_addstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='in_stock',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='out_stock',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(),
        ),
    ]
