# Generated by Django 4.2.4 on 2024-07-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_stock_in_stock_stock_out_stock_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='in_stock',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='out_stock',
            field=models.CharField(max_length=100),
        ),
    ]
