# Generated by Django 4.2.4 on 2024-07-09 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0008_alter_stock_in_stock_alter_stock_out_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
